#127: Allow wiro user to access http headers (closes #127)
buildo/wiro pull request #128
Opened 2018-06-22 13:49 UTC by calippo

Closes #127

## Test Plan

### tests performed

> A Test Plan is used to show what you tested to make sure your code works fine. You should write here all that you did to test, and provide some results of your testing.

> These results can be screenshots, query results, or even just pointers to unit tests that successfully passed.

### tests not performed (domain coverage)

> At times not everything can be tested, and writing what hasn't been tested is just as important as writing what has been tested.

> An example of partial test is a field displaying 4 possible values. If 3 values are tested, with screenshots, and 1 is not, then it should be mentioned here.

2018-06-22 13:59 UTC, calippo commented
I do not superlike how `clientAkkaHttp/src/main/scala/RequestBuilder.scala` is organized... but it's not related to this pr

2018-06-22 15:41 UTC, bytecodeguru reviewed
LGTM, a part for a typo in tests and a doubt about the `OperationParameters` data model. Is it really necessary to expose header values as json instead of plain strings?

2018-06-22 15:41 UTC, bytecodeguru commented on clientAkkaHttp/src/main/scala/RequestBuilder.scala
> +    }
I find it somewhat difficult to read this nested pattern matching, but I suspect that the alternative using something like `Option.flatMap` and `Either.toOption` would be even less readable.

2018-06-22 15:41 UTC, bytecodeguru commented on serverAkkaHttp/src/test/scala/AppSpecs.scala
> +      "allow the user to readm them" in {
`s/readm/read`

2018-06-22 15:41 UTC, bytecodeguru commented on core/src/main/scala/models.scala
> +  parameters: Map[String, Json]
Why `Map[String, Json]` instead of `Map[String, String]`?

2018-06-27 16:38 UTC, calippo commented
@bytecodeguru the pr is now more functional and the returned type is `Map[String, String]`

2018-07-02 09:14 UTC, bytecodeguru requested changes
Just a fix needed for imports.
Some other minor comments, but the rest is 👍

2018-07-02 09:14 UTC, bytecodeguru commented on clientAkkaHttp/src/main/scala/RequestBuilder.scala
> +import cats.implicits._
What about a more specific import:

```scala
import cats.syntax.either._
```

2018-07-02 09:14 UTC, bytecodeguru commented on clientAkkaHttp/src/main/scala/RequestBuilder.scala
> +      headers: List[RawHeader] <- parameters.toOption.map(_.parameters.map(stringPairToHeader).toList)
Great idea the use of explicit types. However I can't understand this passage: 

```scala
parameters <- headersCandidates.headOption // unwrapping the option?
headers <- parameters.toOption // wrapping again?
```

EDIT: it turns out that `Decoder.Result` is an alias for `Either` 👍

2018-07-02 09:14 UTC, bytecodeguru commented on examples/src/main/scala/Doghouse.scala
> +  res map (println(_)) recover { case e: Exception => e.printStackTrace }
Is this really needed in the example or is it for debugging?

2018-07-02 09:14 UTC, bytecodeguru commented on serverAkkaHttp/src/test/scala/AppSpecs.scala
> +          responseAs[OperationParameters].parameters(headerName) should be (headerContent)
Are there any differences between

`responseAs[OperationParameters].parameters should contain (headerName -> headerContent)`

and

`responseAs[OperationParameters].parameters(headerName) should be (headerContent)`?

Is it to test that `OperationParameters` wraps a `Map` instead of a `List`?

2018-07-02 09:18 UTC, calippo commented on examples/src/main/scala/Doghouse.scala
> +  res map (println(_)) recover { case e: Exception => e.printStackTrace }
@bytecodeguru no it's just for convenience

2018-07-02 09:23 UTC, calippo commented on serverAkkaHttp/src/test/scala/AppSpecs.scala
> +          responseAs[OperationParameters].parameters(headerName) should be (headerContent)
@bytecodeguru the first one was meant to test that the key existed, but it turned out it's already testing everything.
We can remove the second one I think.

2018-07-02 09:32 UTC, calippo commented
@bytecodeguru updated

2018-07-02 09:33 UTC, bytecodeguru approved these changes
💯

2018-07-02 09:39 UTC, merged