#60: Reorganize documentation (closes #60)
buildo/wiro pull request #62
Opened 2017-05-29 15:09 UTC by ecamellini

Closes #60

## Test Plan

### tests performed
> A Test Plan is used to show what you tested to make sure your code works fine. You should write here all that you did to test, and provide some results of your testing.

> These results can be screenshots, query results, or even just pointers to unit tests that successfully passed.}

### tests not performed (domain coverage)
> At times not everything can be tested, and writing what hasn't been tested is just as important as writing what has been tested.

> An example of partial test is a field displaying 4 possible values. If 3 values are tested, with screenshots, and 1 is not, then it should be mentioned here.}

2017-05-29 15:16 UTC, ecamellini commented
@calippo at the moment I just substituted the old example in the doc with the one that can be found in `examples/src/main/scala/Server.scala`, which is up-to-date with the current wiro version. Should we re-organise the doc structure in a better way and maybe explain the example step by step too?

2017-05-30 08:30 UTC, gabro commented
I would :)

2017-06-06 09:17 UTC, ecamellini commented
@gabro @calippo I added a step by step example with the corresponding source code. Probably the description of every step can be improved, and also the example itself, but it is better than the one that was there before! Give me some feedback and we can try to improve it together

2017-06-06 09:51 UTC, gabro requested changes

2017-06-06 09:51 UTC, gabro commented on docs/src/main/tut/step-by-step-example.md
> +```scala
when using `tut`, the code blocks must be <code>```tut</code> so that they will be type-checked. See https://github.com/tpolecat/tut

2017-06-06 09:51 UTC, gabro commented on docs/src/main/tut/step-by-step-example.md
> +    @query(name = Some("getUser"))
since you're not renaming the method you can probably just do `@query` (same for `@command` below).
/cc @calippo, right?

2017-06-06 09:51 UTC, gabro commented on docs/src/main/tut/step-by-step-example.md
> +  val users = collection.mutable.Map.empty[Int, User] // Users DB
indentation of this block is off by 1

2017-06-06 09:51 UTC, gabro commented on docs/src/main/tut/step-by-step-example.md
> +val route = UsersServer.usersRouter.buildRoute
I would show a quick example.

2017-06-07 09:39 UTC, calippo commented on docs/src/main/tut/step-by-step-example.md
> +    @query(name = Some("getUser"))
yep

2017-06-07 14:11 UTC, gabro commented
@ecamellini to test things out, run `docs/makeMicrosite` inside `sbt`.

2017-06-07 14:21 UTC, gabro commented
Then you can go into `docs/target/site` and run `jekyll serve`. You should be able to see the site at http://127.0.0.1:4000/wiro/

2017-06-07 14:57 UTC, gabro approved these changes

2017-06-07 15:05 UTC, calippo approved these changes
figo <3

2017-06-07 15:15 UTC, merged